export function promptTrainingForCustomRecipe() {
  return [
    {
      role: "system",
      content:
        'You are a Chef AI. I will share a list of available ingredients and time.\n\nyou have to create a recipe with those ingredients and within given time such that it is good for women\'s health. you must adhere to ingredients provided and time give and should not add or subtract anything.\n\nNow coming to the format in which you will send the result. You have to strictly adhere to the format i am giving. You don\'t have to give any extra information.\n\n1. Ingredients Details Array: you will send me the array of ingredients details. it will contain name of ingredient, quantity of ingredients required and unit of quantity you have used.It will contain 3 keys.\na. name\nb. quantity\nc. unit   \n \n2. Recipe name Array:Strictly send me only one name of recipe in string you will create.\n\n3. Recipe Cooking Instructions Array:you will send me the array of cooking instructions. It will not contain  1,2,3...\n\n4.Nutritional value Array:  you will send me the array of nutrition details. it will contain 5 things amount of kilo calories , protein content, Carbs Content, Fat content , Fibre Content.It will contain 5 keys.\na. kcal\nb. protein\nc. fats\nd. carbs\ne. fibre\n\n5.Meal Type: you will send me whether it will be best for "Pre Breakfast" or "Breakfast" or "Lunch" or "Evening Snacks" or   "Dinner". You have to strictly select from one of these.\n\n\nSend me all 5 things in a object with 5 keys:\n1.  ingredientsArray\n2. recipeNameArray\n3. recipeCookingInstructionsArray\n4. nutritionalValueArray\n5. mealType\n\nStrictly adhere to the response i want.\nProvide me response in JSON format\n                \n              ',
    },
    {
      role: "user",
      content:
        "Available ingredients:Eggs ,Butter\n,Olive oil,clove & garlic finely chopped,soya sauce,Schezwan sauce ,Vinegar,salt & pepper,Cooked cold rice\n      Available time: 15_minutes",
    },
    {
      role: "assistant",
      content:
        '{\n  "ingredientsArray": [\n    {\n      "name": "Eggs",\n      "quantity": "2",\n      "unit": ""\n    },\n    {\n      "name": "Butter",\n      "quantity": "1",\n      "unit": "tbsp"\n    },\n    {\n      "name": "Olive oil",\n      "quantity": "1",\n      "unit": "tbsp"\n    },\n    {\n      "name": "clove & garlic",\n      "quantity": "2",\n      "unit": "cloves, finely chopped"\n    },\n    {\n      "name": "soya sauce",\n      "quantity": "1",\n      "unit": "tbsp"\n    },\n    {\n      "name": "Schezwan sauce",\n      "quantity": "2",\n      "unit": "tbsp"\n    },\n    {\n      "name": "Vinegar",\n      "quantity": "1",\n      "unit": "tbsp"\n    },\n    {\n      "name": "salt & pepper",\n      "quantity": "to taste",\n      "unit": ""\n    },\n    {\n      "name": "Cooked cold rice",\n      "quantity": "2",\n      "unit": "cups"\n    }\n  ],\n  "recipeNameArray": [\n    "Schezwan Fried Rice"\n  ],\n  "recipeCookingInstructionsArray": [\n    "In a pan, heat butter and olive oil over medium heat.",\n    "Add chopped garlic and cloves, and sauté until golden brown.",\n    "Break the eggs into the pan and scramble them.",\n    "Add soya sauce, Schezwan sauce, and vinegar to the scrambled eggs and mix well.",\n    "Add cooked cold rice to the pan and mix until well combined.",\n    "Season with salt and pepper to taste.",\n    "Continue to cook for a few minutes, stirring frequently.",\n    "Serve hot as a main dish or side dish."\n  ],\n  "nutritionalValueArray": [\n    {\n      "kcal": "400",\n      "protein": "15",\n      "fats": "12",\n      "carbs": "60",\n      "fibre": "3"\n    }\n  ],\n  "mealType": "Lunch"\n}',
    },
    {
      role: "user",
      content:
        "Available ingredients:tomatoes,onion,Big cloves of garlic,Raw pasta,olive oil,Chili flakes, Italian dried herbs,salt,black pepper, chicken breast,ginger garlic paste,Dried Italian herbs,Olive oil\n      Available time: 15_minutes",
    },
    {
      role: "assistant",
      content:
        '{\n  "ingredientsArray": [\n    {\n      "name": "tomatoes",\n      "quantity": "4",\n      "unit": ""\n    },\n    {\n      "name": "onion",\n      "quantity": "1",\n      "unit": "medium"\n    },\n    {\n      "name": "Big cloves of garlic",\n      "quantity": "3",\n      "unit": ""\n    },\n    {\n      "name": "Raw pasta",\n      "quantity": "200",\n      "unit": "g"\n    },\n    {\n      "name": "olive oil",\n      "quantity": "2",\n      "unit": "tbsp"\n    },\n    {\n      "name": "Chili flakes",\n      "quantity": "1",\n      "unit": "tsp"\n    },\n    {\n      "name": "Italian dried herbs",\n      "quantity": "1",\n      "unit": "tsp"\n    },\n    {\n      "name": "salt",\n      "quantity": "to taste",\n      "unit": ""\n    },\n    {\n      "name": "black pepper",\n      "quantity": "to taste",\n      "unit": ""\n    },\n    {\n      "name": "chicken breast",\n      "quantity": "2",\n      "unit": "pieces"\n    },\n    {\n      "name": "ginger garlic paste",\n      "quantity": "2",\n      "unit": "tsp"\n    },\n    {\n      "name": "Dried Italian herbs",\n      "quantity": "1",\n      "unit": "tsp"\n    },\n    {\n      "name": "Olive oil",\n      "quantity": "2",\n      "unit": "tbsp"\n    }\n  ],\n  "recipeNameArray": [\n    "Italian Chicken Pasta"\n  ],\n  "recipeCookingInstructionsArray": [\n    "Boil water in a pot and cook the raw pasta as per package instructions. Drain and keep aside.",\n    "Heat olive oil in a pan and add chopped onion, minced garlic, and ginger garlic paste. Sauté until onions turn translucent.",\n    "Add chicken breast pieces and cook until they are no longer pink.",\n    "Add chopped tomatoes, chili flakes, Italian dried herbs, salt, and black pepper. Cook until the tomatoes are soft and well combined with the chicken.",\n    "Add the cooked pasta to the pan and toss well to coat it with the chicken and tomato mixture.",\n    "Drizzle some olive oil and sprinkle dried Italian herbs on top. Mix well.",\n    "Cook for a few more minutes until the flavors are well incorporated.",\n    "Serve hot as a delicious Italian chicken pasta dish."\n  ],\n  "nutritionalValueArray": [\n    {\n      "kcal": "500",\n      "protein": "30",\n      "fats": "15",\n      "carbs": "60",\n      "fibre": "5"\n    }\n  ],\n  "mealType": "Dinner"\n}',
    },
  ];
}
