declare module "react-native-dotenv" {
  // export const NEXT_PUBLIC_FIREBASE_CONFIG: string;
  // export const FIREBASE_SERVICE_ACCOUNT: string;
  // export const DATABASE_URL: string;
  // export const BACKEND_URL: string;
  // export const NEXT_PUBLIC_MIXPANEL: string;
  export const S3_AWS_REGION: string;
  export const ACCESS_KEY: string;
  export const SECRET_KEY: string;
  // export const ALGOLIA_APPLICATION_ID: string;
  // export const ALGOLIA_KEY: string;
  export const API_BASE_URL: string;
  export const BUCKET: string;
  export const IOS_PURCHASES: string;
  export const ANDROID_PURCHASES: string;
  export const MUX_SECRET: string;
  export const MUX_ACCESS_TOKEN_ID: string;
  export const MUX_SECRET_PROD: string;
  export const MUX_ACCESS_TOKEN_ID_PROD: string;
  export const MIXPANEL_KEY: string;
  export const GHOST_API_KEY: string;
  export const BLOG_URL: string;
  export const BACKEND_URL: string;
  export const ALGOLIA_APPLICATION_ID: string;
  export const ALGOLIA_KEY: string;
  export const OPENAI_API_KEY: string;
  export const DEBUG_APPCHECK_AND: string;
  export const DEBUG_APPCHECK_IOS: string;
  export const BRANCH_KEY: string;
}
